#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")"

BUILD_DIR="$(pwd)/docker/.build"
TARGET_DIR="$(pwd)/docker/.target"
mkdir -p "$BUILD_DIR"
mkdir -p "$TARGET_DIR"

source common.sh

build-docker() {
    (cd docker && docker build --quiet -f Dockerfile .)
}

log "Building docker image"
IMAGE_ID="$(build-docker)"

log "Running docker environment"
docker run \
    --user "$(id -u):$(id -g)" \
    --mount "type=bind,source=$(pwd),destination=/usr/src/gtk-static,readonly" \
    --mount "type=bind,source=$CACHE_DIR,destination=/var/cache/gtk-static" \
    --mount "type=bind,source=$BUILD_DIR,destination=/var/tmp/gtk-static" \
    --mount "type=bind,source=$TARGET_DIR,destination=/usr/local/gtk-static" \
    --env "TARGET_DIR=/usr/local/gtk-static" \
    --env "BUILD_DIR=/var/tmp/gtk-static" \
    --env "CACHE_DIR=/var/cache/gtk-static" \
    --workdir /usr/src/gtk-static \
    --interactive \
    --tty \
    "$IMAGE_ID" \
    bash
