FROM alpine:latest

RUN apk add \
    alpine-sdk \
    bash \
    cmake \
    gettext \
    gperf \
    libxml2-utils \
    linux-headers \
    meson \
    musl-libintl \
    ncurses \
    poetry \
    python3 \
    vim \
    xz
